name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry and add to path
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
    - name: "Install Dependencies"
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
